// 台灣外食料理庫（「現在可以吃什麼」用）。
// ⚠️ 全部是「一人份的常見範圍估計值」，非官方檢驗數據——同一道菜依店家做法落差很大，
// UI 必須顯示範圍並標明估計。plain literals designed to be LLM-generatable。
// 文案鐵則：tip 是「怎麼點更順」的實用訣竅，禁療效宣稱（降低LDL/治療），繁體台灣用語。

export interface Dish {
  id: string
  emoji: string
  /** 料理名，8 字內 */
  name: string
  /** 一人份估計範圍 [低點法, 高點法] */
  kcal: [number, number]
  satFat: [number, number]
  chol: [number, number]
  fiber: [number, number]
  /** 怎麼點更順的一句訣竅（10–60 字） */
  tip: string
}

export const DISHES: Dish[] = [
  {
    id: 'shabu',
    emoji: '🍲',
    name: '涮涮鍋',
    kcal: [450, 750],
    satFat: [3, 9],
    chol: [100, 250],
    fiber: [4, 8],
    tip: '昆布湯底選雞肉或海鮮盤，沙茶換和風醬或蔥蒜醬油，菜盤加點好加滿。',
  },
  {
    id: 'spicy-hotpot',
    emoji: '🌶️',
    name: '麻辣鍋',
    kcal: [800, 1400],
    satFat: [15, 30],
    chol: [150, 300],
    fiber: [3, 6],
    tip: '湯底的油喝不得——料撈起來吃就好，鴨血豆腐是好料，肥牛換瘦肉片。',
  },
  {
    id: 'beef-noodle',
    emoji: '🍜',
    name: '牛肉麵',
    kcal: [600, 900],
    satFat: [8, 16],
    chol: [80, 150],
    fiber: [2, 4],
    tip: '半筋半肉改清燉瘦肉、湯喝一半就好，加一份燙青菜補纖維。',
  },
  {
    id: 'plain-noodle',
    emoji: '🥢',
    name: '麵店湯麵',
    kcal: [350, 550],
    satFat: [2, 6],
    chol: [20, 60],
    fiber: [2, 4],
    tip: '陽春麵或餛飩麵負擔不大，配燙青菜加滷豆干海帶，就是很順的一餐。',
  },
  {
    id: 'pasta-red',
    emoji: '🍝',
    name: '義大利麵(紅醬/清炒)',
    kcal: [550, 800],
    satFat: [5, 11],
    chol: [50, 110],
    fiber: [4, 6],
    tip: '茄汁或清炒優於白醬，主料選雞肉或海鮮，起司粉撒一次就好。',
  },
  {
    id: 'pasta-white',
    emoji: '🥛',
    name: '義大利麵(白醬/焗烤)',
    kcal: [750, 1050],
    satFat: [15, 26],
    chol: [80, 160],
    fiber: [2, 4],
    tip: '奶油和起司讓飽脂直接翻倍——想吃的日子把其他兩餐排清爽點。',
  },
  {
    id: 'sushi',
    emoji: '🍣',
    name: '壽司(8–10貫)',
    kcal: [450, 650],
    satFat: [2, 6],
    chol: [80, 180],
    fiber: [1, 3],
    tip: '生魚握壽司優於炙燒美乃滋系，配味噌湯和茶碗蒸，纖維另外想辦法。',
  },
  {
    id: 'sashimi-set',
    emoji: '🐟',
    name: '烤魚/生魚片定食',
    kcal: [500, 750],
    satFat: [3, 8],
    chol: [90, 180],
    fiber: [3, 5],
    tip: '魚的油脂是好油脂，定食的小菜和味噌湯都吃，白飯可以換小碗。',
  },
  {
    id: 'oyakodon',
    emoji: '🍚',
    name: '丼飯(親子丼/牛丼)',
    kcal: [600, 850],
    satFat: [6, 12],
    chol: [200, 380],
    fiber: [1, 3],
    tip: '蛋和肉讓膽固醇偏高——先看今天膽固醇環還剩多少再決定。',
  },
  {
    id: 'ramen',
    emoji: '🍥',
    name: '日式拉麵',
    kcal: [700, 1000],
    satFat: [12, 22],
    chol: [100, 200],
    fiber: [2, 3],
    tip: '豚骨湯的飽脂在湯裡——麵和料吃完、湯淺嚐即止，叉燒選瘦的。',
  },
  {
    id: 'bento-chicken',
    emoji: '🍱',
    name: '雞腿便當',
    kcal: [750, 950],
    satFat: [8, 14],
    chol: [120, 180],
    fiber: [3, 5],
    tip: '滷或烤優於炸，雞皮剝掉現省 5g 飽脂，三格配菜選深綠色的。',
  },
  {
    id: 'bento-pork',
    emoji: '🍖',
    name: '排骨便當',
    kcal: [800, 1050],
    satFat: [12, 20],
    chol: [100, 160],
    fiber: [3, 5],
    tip: '炸衣吸滿油——把外衣剝一半，或改點滷排骨，配菜多夾一格。',
  },
  {
    id: 'buffet',
    emoji: '🥘',
    name: '自助餐',
    kcal: [500, 850],
    satFat: [5, 13],
    chol: [80, 180],
    fiber: [5, 9],
    tip: '最好控的外食：一掌心的肉＋兩格深綠蔬菜＋滷豆腐，飯選糙米或半碗。',
  },
  {
    id: 'braised-pork-rice',
    emoji: '🥣',
    name: '滷肉飯+燙青菜',
    kcal: [550, 750],
    satFat: [8, 15],
    chol: [60, 120],
    fiber: [3, 5],
    tip: '滷肉飯點小碗解饞就好，靠燙青菜和滷蛋豆干把這餐撐起來。',
  },
  {
    id: 'turkey-rice',
    emoji: '🍗',
    name: '火雞肉飯',
    kcal: [450, 650],
    satFat: [4, 8],
    chol: [60, 110],
    fiber: [2, 4],
    tip: '雞絲比滷肉飯清爽，配一盤燙青菜和筍絲，嘉義人的智慧。',
  },
  {
    id: 'dumplings',
    emoji: '🥟',
    name: '水餃(10顆)',
    kcal: [500, 700],
    satFat: [8, 14],
    chol: [80, 140],
    fiber: [2, 4],
    tip: '高麗菜韭菜餡優於純肉餡，配酸辣湯不如配紫菜蛋花湯，醬別調太油。',
  },
  {
    id: 'pho',
    emoji: '🍲',
    name: '越南河粉',
    kcal: [400, 600],
    satFat: [3, 7],
    chol: [50, 120],
    fiber: [2, 4],
    tip: '清湯生牛肉片是外食的資優生，豆芽九層塔加好加滿，炸春捲跳過。',
  },
  {
    id: 'bibimbap',
    emoji: '🍳',
    name: '韓式石鍋拌飯',
    kcal: [600, 800],
    satFat: [6, 11],
    chol: [200, 300],
    fiber: [4, 7],
    tip: '蔬菜多是優點，蛋黃拌進去前看一眼膽固醇環，辣醬半匙就夠味。',
  },
  {
    id: 'tofu-stew',
    emoji: '🫕',
    name: '韓式豆腐鍋',
    kcal: [450, 680],
    satFat: [6, 12],
    chol: [150, 260],
    fiber: [3, 6],
    tip: '豆腐海鮮組合不錯，蛋可以請店家不加，小菜的海帶豆芽多吃。',
  },
  {
    id: 'salad-bowl',
    emoji: '🥗',
    name: '沙拉碗(雞胸/鮭魚)',
    kcal: [350, 600],
    satFat: [3, 9],
    chol: [80, 150],
    fiber: [6, 10],
    tip: '纖維一次補足的選擇——醬選油醋，凱薩和胡麻醬熱量差三倍。',
  },
  {
    id: 'subway',
    emoji: '🥖',
    name: '潛艇堡',
    kcal: [400, 650],
    satFat: [4, 10],
    chol: [40, 100],
    fiber: [3, 6],
    tip: '全麥麵包＋雞胸或鮪魚，蔬菜全加，起司和美乃滋二選一就好。',
  },
  {
    id: 'fastfood',
    emoji: '🍔',
    name: '速食漢堡',
    kcal: [550, 1300],
    satFat: [8, 25],
    chol: [60, 180],
    fiber: [2, 5],
    tip: '單點漢堡＋沙拉代替套餐薯條可樂，熱量直接砍半，偶爾吃無妨。',
  },
  {
    id: 'salted-chicken',
    emoji: '🐓',
    name: '鹹水雞',
    kcal: [300, 550],
    satFat: [3, 8],
    chol: [100, 180],
    fiber: [3, 6],
    tip: '宵夜界的好選擇：雞胸部位＋大把蔬菜，蔥油和辣醬請老闆少一半。',
  },
  {
    id: 'conv-store',
    emoji: '🏪',
    name: '超商輕食組合',
    kcal: [350, 550],
    satFat: [2, 6],
    chol: [20, 230],
    fiber: [3, 6],
    tip: '御飯糰＋無糖豆漿＋生菜沙拉是安全牌；加茶葉蛋前看膽固醇環。',
  },
  {
    id: 'sweet-potato-egg',
    emoji: '🍠',
    name: '地瓜+茶葉蛋',
    kcal: [250, 380],
    satFat: [1.5, 3.5],
    chol: [190, 230],
    fiber: [3, 5],
    tip: '輕食經典組合，纖維和蛋白質都有；蛋的膽固醇記得算進今天額度。',
  },
  {
    id: 'egg-pancake',
    emoji: '🫓',
    name: '早餐店蛋餅',
    kcal: [400, 600],
    satFat: [6, 11],
    chol: [200, 280],
    fiber: [2, 4],
    tip: '配無糖豆漿別配奶茶；加蔬菜的蛋餅比起司培根款順很多。',
  },
  {
    id: 'soba',
    emoji: '🎋',
    name: '蕎麥涼麵',
    kcal: [400, 580],
    satFat: [2, 5],
    chol: [30, 90],
    fiber: [3, 5],
    tip: '夏天的輕負擔選擇，麻醬換和風醬油差很多，加顆溫泉蛋看額度。',
  },
  {
    id: 'oatmeal-yogurt',
    emoji: '🥣',
    name: '燕麥優格碗',
    kcal: [300, 480],
    satFat: [3, 8],
    chol: [10, 40],
    fiber: [5, 8],
    tip: '燕麥的水溶性纖維是好朋友，優格選無糖，堅果一小把就好。',
  },
]
